#define main sta_ker
__asm__(
".text \n"
".align 4 \n"
"cmdline: \n"
".string \"" START "\" \n"
"envline: \n"
".string \"TZ=JST-9\" \n"
".align 4 \n"
"_args: \n"
".long 1 \n"
".long cmdline \n"
".long 0 \n"
".long envline \n"
".long 0 \n"
".global " START " \n"
".type " START ",%function \n"
".align 4 \n"
START ": \n"
"2:	ldr r0, =_args \n"
"	bl " START "_c \n"
".weak _DYNAMIC \n"
".hidden _DYNAMIC \n"
".align 2 \n"
"1:	.word _DYNAMIC-2b \n"
);
